import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export function useLanguage() {
  return useContext(LanguageContext)
}

// ── All UI text in English and Kinyarwanda ──────────────────────────────────
export const translations = {
  en: {
    // Navbar
    nav_dashboard: 'Dashboard',
    nav_training: 'Training',
    nav_marketplace: 'Marketplace',
    nav_admin: 'Admin',
    nav_signout: 'Sign Out',
    nav_menu: 'Menu',

    // Auth
    auth_tagline: 'Skills-to-Income Platform',
    auth_welcome: 'Welcome back',
    auth_email: 'Email Address',
    auth_password: 'Password',
    auth_signin: 'Sign In',
    auth_signing_in: 'Signing in...',
    auth_no_account: "Don't have an account?",
    auth_signup_free: 'Sign up free',
    auth_have_account: 'Already have an account?',
    auth_signin_link: 'Sign in',
    auth_step1: 'Account Details',
    auth_step2: 'Ability Profile',
    auth_fullname: 'Full Name',
    auth_fullname_placeholder: 'Your full name',
    auth_email_placeholder: 'you@example.com',
    auth_password_min: 'Min. 6 characters',
    auth_confirm_password: 'Confirm Password',
    auth_confirm_placeholder: 'Repeat password',
    auth_phone: 'Phone Number',
    auth_phone_placeholder: '+250 7XX XXX XXX',
    auth_location: 'Location / City',
    auth_location_placeholder: 'e.g. Kigali, Rwanda',
    auth_continue: 'Continue →',
    auth_back: '← Back',
    auth_create_account: 'Create Account',
    auth_creating: 'Creating Account...',
    auth_disability_type: 'Disability Type',
    auth_disability_placeholder: 'Select your disability type',
    auth_comfortable: 'What are you comfortable doing? (select all that apply)',

    // Complete profile
    complete_title: 'Complete Your Profile',
    complete_subtitle: 'Tell us about yourself so we can match you to the right opportunities',
    complete_save: 'Save Profile & Continue →',
    complete_saving: 'Saving...',

    // Dashboard
    dash_welcome: 'Welcome back',
    dash_location_not_set: 'Location not set',
    dash_total_earned: 'Total Earned',
    dash_modules_completed: 'Modules Completed',
    dash_certificates: 'Certificates Earned',
    dash_skill_tracks: 'Skill Tracks',
    dash_overall_progress: 'Overall Progress',
    dash_your_tracks: 'Your Skill Tracks',
    dash_tracks_subtitle: 'Based on your profile, our engine assigned you these tracks. Each track has training modules and income opportunities.',
    dash_primary: 'Primary',
    dash_modules_label: 'modules',
    dash_start_training: 'Start Training →',
    dash_your_certs: 'Your Certificates',
    dash_quick_actions: 'Quick Actions',
    dash_continue_training: 'Continue Training',
    dash_browse_market: 'Browse Marketplace',
    dash_list_product: 'List a Product',

    // Training
    train_title: 'Training Modules',
    train_subtitle: 'Complete modules to earn certificates and unlock income opportunities.',
    train_no_modules: 'No modules available for this track yet.',
    train_select_module: 'Select a module to start learning',
    train_level: 'Level',
    train_duration: 'Duration',
    train_completed: 'Completed',
    train_quiz_ready: 'Ready to test your knowledge?',
    train_quiz_pass_info: 'Complete the quiz with 70% or higher to earn your certificate.',
    train_start_quiz: 'Start Quiz',
    train_questions: 'questions',
    train_quiz_title: 'Quiz',
    train_submit_quiz: 'Submit Quiz',
    train_passed: 'Congratulations! You passed!',
    train_score: 'Score',
    train_cert_saved: 'Your certificate has been added to your profile.',
    train_saving_cert: 'Saving your certificate...',
    train_failed: 'Not quite — you scored',
    train_need_70: 'You need 70% to pass. Review the video and try again.',
    train_retry: 'Retry Quiz',
    train_answer_review: 'Answer Review',
    train_your_answer: 'Your answer',
    train_correct: '(correct)',
    train_wrong: '(wrong)',
    train_correct_answer: 'Correct',

    // Marketplace
    market_title: 'Marketplace',
    market_subtitle: 'Find gig work or sell your handmade products',
    market_post_gig: '+ Post a Gig',
    market_list_product: '+ List a Product',
    market_gig_tasks: 'Gig Tasks',
    market_product_store: 'Product Store',
    market_post_gig_title: 'Post a New Gig Task',
    market_task_title: 'Task Title',
    market_task_placeholder: 'e.g. Data entry for 500 records',
    market_category: 'Category',
    market_description: 'Description',
    market_desc_placeholder: 'Describe the task in detail...',
    market_budget: 'Budget (RWF)',
    market_budget_placeholder: 'e.g. 15000',
    market_deadline: 'Deadline',
    market_cancel: 'Cancel',
    market_post_btn: 'Post Gig',
    market_posting: 'Posting...',
    market_list_title: 'List a Product for Sale',
    market_product_name: 'Product Name',
    market_product_placeholder: 'e.g. Handwoven basket',
    market_price: 'Price (RWF)',
    market_price_placeholder: 'e.g. 5000',
    market_image_url: 'Image URL (optional)',
    market_list_btn: 'List Product',
    market_listing: 'Listing...',
    market_no_gigs: 'No gigs posted yet. Be the first to post one!',
    market_no_products: 'No products listed yet. List your first product!',
    market_applicants: 'applicants',
    market_apply: 'Apply Now',
    market_applied: 'Applied',
    market_contact_seller: 'Contact Seller',
    market_loading: 'Loading gigs...',
    market_gig_posted: 'Gig posted successfully!',
    market_product_listed: 'Product listed successfully!',
    market_application_sent: 'Application submitted!',
    market_desc_product_placeholder: 'Describe your product...',

    // Admin
    admin_title: 'Admin Panel',
    admin_subtitle: 'NGO / Coordinator Dashboard',
    admin_total_users: 'Total Users',
    admin_certs_issued: 'Certificates Issued',
    admin_open_gigs: 'Open Gigs',
    admin_total_earnings: 'Total Earnings Tracked',
    admin_users_tab: 'Users',
    admin_gigs_tab: 'Gigs',
    admin_products_tab: 'Products',
    admin_search: 'Search users by name or email...',
    admin_loading: 'Loading users...',
    admin_name: 'Name',
    admin_email: 'Email',
    admin_disability: 'Disability',
    admin_tracks: 'Tracks',
    admin_modules_done: 'Modules Done',
    admin_certs: 'Certs',
    admin_earnings: 'Earnings',
    admin_role: 'Role',
    admin_actions: 'Actions',
    admin_update_earnings: 'Earnings',
    admin_make_admin: 'Admin',
    admin_title_col: 'Title',
    admin_budget: 'Budget',
    admin_posted_by: 'Posted By',
    admin_applicants: 'Applicants',
    admin_status: 'Status',
    admin_phone: 'Phone',
    admin_location: 'Location',
    admin_modules_completed: 'Modules Completed',
    admin_certificates: 'Certificates',
    admin_total_earned: 'Total Earnings',

    // Voice reader
    voice_read: 'Read Page',
    voice_stop: 'Stop Reading',
    voice_reading: 'Reading...',

    // Language toggle
    lang_toggle: 'Kinyarwanda',
  },

  rw: {
    // Navbar
    nav_dashboard: 'Imbonerahamwe',
    nav_training: 'Amahugurwa',
    nav_marketplace: 'Isoko',
    nav_admin: 'Ubuyobozi',
    nav_signout: 'Sohoka',
    nav_menu: 'Menyu',

    // Auth
    auth_tagline: 'Urubuga rwo Guhindura Ubushobozi mu Musaruro',
    auth_welcome: 'Murakaza neza',
    auth_email: 'Imeyili',
    auth_password: 'Ijambo ry\'ibanga',
    auth_signin: 'Injira',
    auth_signing_in: 'Injira...',
    auth_no_account: 'Nta konti ufite?',
    auth_signup_free: 'Iyandikishe ubuntu',
    auth_have_account: 'Usanzwe ufite konti?',
    auth_signin_link: 'Injira',
    auth_step1: 'Amakuru y\'Konti',
    auth_step2: 'Umwirondoro w\'Ubushobozi',
    auth_fullname: 'Amazina Yuzuye',
    auth_fullname_placeholder: 'Amazina yawe yuzuye',
    auth_email_placeholder: 'wowe@urugero.com',
    auth_password_min: 'Nibura inyuguti 6',
    auth_confirm_password: 'Emeza Ijambo ry\'Ibanga',
    auth_confirm_placeholder: 'Subiramo ijambo ry\'ibanga',
    auth_phone: 'Nimero ya Telefoni',
    auth_phone_placeholder: '+250 7XX XXX XXX',
    auth_location: 'Aho Utuye / Umujyi',
    auth_location_placeholder: 'urugero: Kigali, Rwanda',
    auth_continue: 'Komeza →',
    auth_back: '← Subira',
    auth_create_account: 'Fungura Konti',
    auth_creating: 'Gufungura Konti...',
    auth_disability_type: 'Ubwoko bw\'Ubumuga',
    auth_disability_placeholder: 'Hitamo ubwoko bw\'ubumuga bwawe',
    auth_comfortable: 'Ni iki ukora neza? (hitamo byose bishoboka)',

    // Complete profile
    complete_title: 'Uzuza Umwirondoro Wawe',
    complete_subtitle: 'Tubwire ibyerekeye wewe kugira ngo tugufatanye n\'amahirwe akwiye',
    complete_save: 'Bika Umwirondoro & Komeza →',
    complete_saving: 'Kubika...',

    // Dashboard
    dash_welcome: 'Murakaza neza',
    dash_location_not_set: 'Aho utuye ntikubitswe',
    dash_total_earned: 'Amafaranga Yose Waronse',
    dash_modules_completed: 'Amasomo Yarangiye',
    dash_certificates: 'Impamyabushobozi Zaronse',
    dash_skill_tracks: 'Inzira z\'Ubushobozi',
    dash_overall_progress: 'Aho Ugeze Muri Rusange',
    dash_your_tracks: 'Inzira Zawe z\'Ubushobozi',
    dash_tracks_subtitle: 'Dushingiye ku mwirondoro wawe, sisitemu yawe yakugennye inzira zizi. Inzira yose ifite amasomo n\'amahirwe yo gukora.',
    dash_primary: 'Ibanze',
    dash_modules_label: 'amasomo',
    dash_start_training: 'Tangira Amahugurwa →',
    dash_your_certs: 'Impamyabushobozi Zawe',
    dash_quick_actions: 'Ibikorwa Byihuse',
    dash_continue_training: 'Komeza Amahugurwa',
    dash_browse_market: 'Reba Isoko',
    dash_list_product: 'Shyira Igicuruzwa',

    // Training
    train_title: 'Amasomo y\'Amahugurwa',
    train_subtitle: 'Rangiza amasomo kugira ngo uronke impamyabushobozi n\'amahirwe yo gukora.',
    train_no_modules: 'Nta masomo aboneka muri iyi nzira ubu.',
    train_select_module: 'Hitamo isomo kugira ngo utangire kwiga',
    train_level: 'Urwego',
    train_duration: 'Igihe',
    train_completed: 'Yarangiye',
    train_quiz_ready: 'Witeguye kugenzura ubumenyi bwawe?',
    train_quiz_pass_info: 'Rangiza ikizamini ufite 70% cyangwa hejuru kugira ngo uronke impamyabushobozi.',
    train_start_quiz: 'Tangira Ikizamini',
    train_questions: 'ibibazo',
    train_quiz_title: 'Ikizamini',
    train_submit_quiz: 'Ohereza Ikizamini',
    train_passed: 'Congratulations! Wapfuye!',
    train_score: 'Amanota',
    train_cert_saved: 'Impamyabushobozi yawe yongewe ku mwirondoro wawe.',
    train_saving_cert: 'Kubika impamyabushobozi yawe...',
    train_failed: 'Ntabwo bihagije — waronse',
    train_need_70: 'Ukeneye 70% kugira ngo upfuke. Subiramo videwo hanyuma ugerageze.',
    train_retry: 'Subiramo Ikizamini',
    train_answer_review: 'Kureba Ibisubizo',
    train_your_answer: 'Igisubizo cyawe',
    train_correct: '(nibyo)',
    train_wrong: '(sibyo)',
    train_correct_answer: 'Igisubizo Nyacyo',

    // Marketplace
    market_title: 'Isoko',
    market_subtitle: 'Shaka akazi ka gig cyangwa gurisha ibicuruzwa byawe byakozwe n\'intoki',
    market_post_gig: '+ Shyira Akazi',
    market_list_product: '+ Shyira Igicuruzwa',
    market_gig_tasks: 'Imirimo ya Gig',
    market_product_store: 'Iduka ry\'Ibicuruzwa',
    market_post_gig_title: 'Shyira Akazi Gashya',
    market_task_title: 'Umutwe w\'Akazi',
    market_task_placeholder: 'urugero: Kwinjiza amakuru 500',
    market_category: 'Icyiciro',
    market_description: 'Ibisobanuro',
    market_desc_placeholder: 'Sobanura akazi mu buryo burambuye...',
    market_budget: 'Ingengo y\'Imari (RWF)',
    market_budget_placeholder: 'urugero: 15000',
    market_deadline: 'Igihe Kizarangirira',
    market_cancel: 'Reka',
    market_post_btn: 'Shyira Akazi',
    market_posting: 'Gushyira...',
    market_list_title: 'Shyira Igicuruzwa Kugurisha',
    market_product_name: 'Izina ry\'Igicuruzwa',
    market_product_placeholder: 'urugero: Agaseke gakozwe n\'intoki',
    market_price: 'Igiciro (RWF)',
    market_price_placeholder: 'urugero: 5000',
    market_image_url: 'URL y\'Ifoto (si ngombwa)',
    market_list_btn: 'Shyira Igicuruzwa',
    market_listing: 'Gushyira...',
    market_no_gigs: 'Nta mirimo ishyizwe ubu. Ube uwa mbere!',
    market_no_products: 'Nta bicuruzwa bishyizwe ubu. Shyira igicuruzwa cya mbere!',
    market_applicants: 'abasaba',
    market_apply: 'Saba Ubu',
    market_applied: 'Wasabye',
    market_contact_seller: 'Vugana n\'Ugurisha',
    market_loading: 'Gushakisha imirimo...',
    market_gig_posted: 'Akazi kashyizwe neza!',
    market_product_listed: 'Igicuruzwa gishyizwe neza!',
    market_application_sent: 'Ubusabe bwoherejwe!',
    market_desc_product_placeholder: 'Sobanura igicuruzwa cyawe...',

    // Admin
    admin_title: 'Imbonerahamwe y\'Ubuyobozi',
    admin_subtitle: 'Imbonerahamwe ya NGO / Umuyobozi',
    admin_total_users: 'Abakoresha Bose',
    admin_certs_issued: 'Impamyabushobozi Zatanzwe',
    admin_open_gigs: 'Imirimo Ifunguye',
    admin_total_earnings: 'Amafaranga Yose Akurikiranwa',
    admin_users_tab: 'Abakoresha',
    admin_gigs_tab: 'Imirimo',
    admin_products_tab: 'Ibicuruzwa',
    admin_search: 'Shakisha abakoresha mu mazina cyangwa imeyili...',
    admin_loading: 'Gushakisha abakoresha...',
    admin_name: 'Amazina',
    admin_email: 'Imeyili',
    admin_disability: 'Ubumuga',
    admin_tracks: 'Inzira',
    admin_modules_done: 'Amasomo Yarangiye',
    admin_certs: 'Impamyabushobozi',
    admin_earnings: 'Amafaranga',
    admin_role: 'Uruhare',
    admin_actions: 'Ibikorwa',
    admin_update_earnings: 'Amafaranga',
    admin_make_admin: 'Ubuyobozi',
    admin_title_col: 'Umutwe',
    admin_budget: 'Ingengo y\'Imari',
    admin_posted_by: 'Washyizwe Na',
    admin_applicants: 'Abasaba',
    admin_status: 'Imiterere',
    admin_phone: 'Telefoni',
    admin_location: 'Aho Utuye',
    admin_modules_completed: 'Amasomo Yarangiye',
    admin_certificates: 'Impamyabushobozi',
    admin_total_earned: 'Amafaranga Yose',

    // Voice reader
    voice_read: 'Soma Urupapuro',
    voice_stop: 'Hagarika Gusoma',
    voice_reading: 'Gusoma...',

    // Language toggle
    lang_toggle: 'English',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('ab_lang') || 'en')

  function toggleLanguage() {
    const next = lang === 'en' ? 'rw' : 'en'
    setLang(next)
    localStorage.setItem('ab_lang', next)
  }

  function t(key) {
    return translations[lang][key] || translations['en'][key] || key
  }

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
